<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="LumexUI" Version="2.3.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.2"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.2" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Congratulator.SharedKernel.Contracts\Congratulator.SharedKernel.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Button\Button.razor" />
      <_ContentIncludedByDefault Remove="Components\ConfirmDialog\ConfirmDialog.razor" />
      <_ContentIncludedByDefault Remove="Components\PersonCard\PersonCard.razor" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
      <Content Remove="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    </ItemGroup>
    
</Project>
